services:
  mosquitto:
    image: docker.io/iegomez/mosquitto-go-auth:latest
    container_name: mosquitto
    restart: unless-stopped
    ports:
     - "1883:1883"
     - "9001:9001"
    environment:
     - MOSQUITTO_USERS_B64 
    volumes:
     - ./mosquitto/config:/mosquitto/config
     - ./mosquitto/data:/mosquitto/data
     - ./mosquitto/log:/mosquitto/log
     - ./mosquitto/entrypoint.sh:/mosquitto/entrypoint.sh:ro
    entrypoint: ["/mosquitto/entrypoint.sh"]
    depends_on:
      - backend
    networks:
      - mqtt-net
  backend:
    build: ./backend
    container_name: mqtt-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./backend/users.json:/app/users.json:ro
    environment:
      - JWT_SECRET=ccb9f1e58a4d0332f844d2c3a53b15274a99fc8fe34abf45cce1d2cf87e8994e
    networks:
      - mqtt-net
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    ports:
#      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/ssl/private:/etc/ssl/private:ro
    networks:
      - mqtt-net

networks:
  mqtt-net:

volumes:
  caddy_data:
  caddy_config:
