mosquitto:
    users:
        pits_crew: ENC[AES256_GCM,data:KHQ2TVDNEQ==,iv:WF6sMPrkZoA9x8QYmMwjzrMhJOVHVO/4rlsUDo0L7JQ=,tag:08kvDUxQp65ubtKsRGD8hg==,type:str]
        karch: ENC[AES256_GCM,data:PQJd1a8xShKbUQ==,iv:Zx0OWDQVkr4yJRaacfhMdLOuBoY5qcw1T0uqi7DXq5U=,tag:s3pJL9p/qA7+pzoiZ2m6zA==,type:str]
        sting: ENC[AES256_GCM,data:/UqDDvgFZDI=,iv:iZRu+5rcFd50tpHSIwIqYrNVPnRz/q3KIzJ/N58IGgw=,tag:5hXr9v7mWBrGVRkFtdAdGw==,type:str]
sops:
    age:
        - recipient: age17n68swgcu4yfhl8fyldu0a0rjqrj4mzjvu9un47w72ak0j8y393sn5xtwy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqR2c4Wmh0dVM1UCs3cDJm
            RHVTV3NuY2NyWUE1cWpHaDczUHBLdksybWtZCjBRVXRWM0lsV1ZOWWtYU2gzcmZa
            ZThzRlgyRkxVUGhCb3FoRW5QVmpuV2cKLS0tIEUzaGhvcVgvb2RsUEJxbWUxMm0w
            dzUxdEYwc2ZNMGUrWXRHYmpkQXlOY3cKPajTNKclAi/HzsTb8m7Nng9s89ec+OYg
            76NQYWeiDlqzAgGbnVwTpypPLzLcSxAA7Pu9kaIQvv3SZCUyXtgFOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-04T13:24:59Z"
    mac: ENC[AES256_GCM,data:/xJtjzsxKvKAvir/mK+wXxQdJgQQ9sWXHK0cRttRvsQdoG47QRKrpA8TuSTsh9Tn0R4aMsQUIPVFck+AdH2PaxFhdFTzP34hiWQfxYK2ZecpMcQ6MYAxeCqsMs+scmydJuNXxHbVd/MVGN/bizuyCkuIzLTMPdJ6T8Od016hpfc=,iv:/NxfXbtlxBFjx7mTT7PN2F5oCbJqt8/f/zdOMedyMhY=,tag:EpY2uImpUhjdP7SWrDTRYg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
